package com.solutions.euler;

import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class AddEvenFibsUtilTest{


    /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */
    @Test
    public void testAddEvenFibs_FirstTen(){

        int result = AddEvenFibsUtil.addEvenFibs(90);

        assertEquals(44, result);
    }

    @Test
    public void testAddEvenFibs_SolveEulerProblem2(){

        int result = AddEvenFibsUtil.addEvenFibs(4000000);

        assertEquals(4613732, result);
    }

}